OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: public.com
    Specs:
      - Hostname: orderer  # orderer.public.com

PeerOrgs:
  # ---------------------------------------------------------------------------
  # Org1
  # ---------------------------------------------------------------------------
  - Name: Org1
    Domain: org1.public.com
    EnableNodeOUs: false
    Template:
      Count: 2
    Users:
      Count: 1

  # ---------------------------------------------------------------------------
  # Org2: See "Org1" for full specification
  # ---------------------------------------------------------------------------
  - Name: Org2
    Domain: org2.public.com
    EnableNodeOUs: false
    Template:
      Count: 2
    Users:
      Count: 1

  - Name: Org3
    Domain: org3.public.com
    EnableNodeOUs: false
    Template:
      Count: 2
    Users:
      Count: 1
